### ISSUE TITLE
UI/UX Design Documents

### ISSUE THREAD

**Issue by JessicaFornetti** [2024-CMPU9010-GROUP-3/magpie#130]
# Information Architecture
These tasks represents creation of our information architecture for the UI/UX

- [x] Create a mind map
- [x] Create a user persona
- [x] Create a user journey
- [x] Create a sitemap
- [ ] Create a low fidelity prototype
- [ ] Create a Wireframe
- [ ] Create a medium fidelity prototype
- [ ] Create a high fidelity prototype

**Comment by KaustubhTrivedi** [comment]
# Information Architecture
These tasks represents creation of our information architecture for the UI/UX

- [ ] Create a requirements specification document
- [ ] Create a mind map
- [ ] Create a competitor analysis document
- [ ] Create a user persona
- [ ] Card Sorting
- [ ] Create a user journey
- [ ] Create a sitemap
- [ ] Create a low fidelity prototype
- [ ] Create a Wireframe
- [ ] Create a medium fidelity prototype
- [ ] Create a high fidelity prototype

**Comment by KaustubhTrivedi** [comment]
@Stevendu666 What is the progress on the prototypes?
